version: 2
jobs:
  build:
    working_directory: ~/target/
    docker:
      - image: circleci/python:3.7.6
        environment:
          CIRCLECI: true
          USER: user
          DB_NAME: target
          PORT: 5432
          DB_ENGINE: django.contrib.gis.db.backends.postgis
          BROKER_URL: redis://localhost:6379
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          ENV_ROLE: ci
          PIPENV_VENV_IN_PROJECT: true
      - image: mdillon/postgis
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: target
          POSTGRES_PASSWORD: ""
      - image: redis
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: sudo apt install -y gdal-bin
      - run: sudo pip3 install -r requirements.txt
      - run: sudo apt-get install redis-server
      - run: sudo redis-server --daemonize yes
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/"
      - run: flake8
      - run: coverage run -a --source=. manage.py test --exclude-tag=pytest
      - run: coverage run -a -m pytest
      - run: coverage report --fail-under=90
